name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.interdimension.${project.artifactId}
author: Areson
api-version: 1.16

commands:
  setprobability:
    usage: /<command>
    permission: areson.interdimension.admin

  setdestination:
    usage: /<command>
    permission: areson.interdimension.admin

permissions:
  areson.interdimension.admin:
    default: op
