name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.interdimension.${project.artifactId}
author: Areson
api-version: 1.16

commands:
  reloadportals:
    usage: /<command>
    permission: areson.interdimension.admin

  setportalprobability:
    usage: /<command>
    permission: areson.interdimension.admin

  setportaldestination:
    usage: /<command>
    permission: areson.interdimension.admin

  toggleportals:
    usage: /<command>
    permission: areson.interdimension.admin

permissions:
  areson.interdimension.admin:
    default: op
